// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4_WWFDHteYVrSj2-H8YPEyvZTXRLCdo',
    appId: '1:404739700685:android:cd4c3417edd4dee1187684',
    messagingSenderId: '404739700685',
    projectId: 'dev-cois-attendance',
    databaseURL: 'https://dev-cois-attendance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dev-cois-attendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmtyCb4GsXw1wROYp7Cp8sQV4--gbqgw',
    appId: '1:404739700685:ios:58db7ae315cf92f5187684',
    messagingSenderId: '404739700685',
    projectId: 'dev-cois-attendance',
    databaseURL: 'https://dev-cois-attendance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dev-cois-attendance.appspot.com',
    iosClientId: '404739700685-jonoh1n5arno8j4ontok7dch2no8snbk.apps.googleusercontent.com',
    iosBundleId: 'com.niketpatel.attendance',
  );
}
